  OrdersResponse: `interface OrdersResponse {\n  items: OrderSummary[];\n  isLastPage: boolean;\n  nextPageNumber: number | null;\n  currentPage: number;\n  totalPages: number;\n}`,
  OrderSummary: `interface OrderSummary {\n  id: string;\n  date?: { _seconds?: number; _nanoseconds?: number } | string;\n  status?: string;\n  attachmentsCount?: number;\n  marketPlaceId?: string;\n  productsCount?: number;\n  discountCode?: string;\n  products?: OrderProductItem[];\n  payment?: OrderPaymentInfo;\n  customer?: CustomerDetails & { name?: string; phone?: string; email?: string; address?: string; gov?: string };\n  courier?: { id?: string; name?: string };\n}`,
  OrderPriceResponse: `interface OrderPriceResponse {\n  itemsPrice: number;\n  shippingFees: number;\n  discount: number;\n  totalPrice: number;\n}`,
  CreateOrderResponseData: `interface CreateOrderResponseData {\n  id?: string;\n  date?: { _seconds?: number; _nanoseconds?: number } | string;\n  status?: string;\n  link?: string;\n  amount?: number;\n  order?: OrderSummary;\n}`,
  CartResponse: `interface CartResponse {\n  items: CartItem[];\n  totalPrice: number;\n  currency?: string;\n  totalQuantity?: number;\n  productsCount?: number;\n}`,
  CartItem: `interface CartItem {\n  id: string;\n  name?: string;\n  image?: string;\n  categoryName?: string;\n  subCategoryName?: string;\n  link?: string;\n  variantId?: string;\n  variantDisplay?: Record<string, any>;\n  quantity?: number;\n  maxQuantity?: number;\n  price?: number;\n  totalPrice?: number;\n}`,
  CustomPage: `interface CustomPage {\n  id: string;\n  body?: string;\n  title?: string;\n  link?: string;\n}`,
// This file is auto-generated for documentation UI. It exposes the SDK types as JSON for the docs UI.
window.VONDERA_TYPES = {
  ApiResponse: `interface ApiResponse<T = any> {\n  status: number;\n  message: string;\n  data: T | null;\n}`,
  WishlistItem: `interface WishlistItem {\n  id: string;\n  name: string;\n  description?: string;\n  price?: number;\n  crossedPrice?: number;\n  quantity?: number;\n  mainImage?: ImageSizes | null;\n  images?: ImageSizes[];\n  link?: string;\n  categoryName?: string;\n  categoryId?: string;\n  subCategoryId?: string;\n  subCategoryName?: string;\n  sku?: string;\n  variantsDisplay?: Record<string, string[] | string>;\n  variantsSettings?: VariantSetting[];\n  rating?: { average?: number; count?: number };\n  isAvailable?: boolean;\n}`,
  WishlistResponse: `interface WishlistResponse {\n  items: WishlistItem[];\n  isLastPage: boolean;\n  nextPageNumber: number | null;\n  currentPage: number;\n  totalPages: number;\n}`,
  ProductSummary: `interface ProductSummary {\n  id: string;\n  name?: string;\n  description?: string;\n  price?: number;\n  crossedPrice?: number;\n  mainImage?: ImageSizes | null;\n  images?: string[] | ImageSizes[];\n  link?: string;\n  categoryName?: string;\n  categoryLink?: string;\n  subCategoryName?: string;\n  subCategoryId?: string;\n  quantity?: number;\n  isAvailable?: boolean;\n  currency?: string;\n  country?: string;\n  variantsDisplay?: Record<string, string[] | string>;\n  variantsSettings?: VariantSetting[] | Record<string, any>;\n  rating?: { average?: number; count?: number };\n}`,
  ProductListResponse: `interface ProductListResponse {\n  items: ProductSummary[];\n  isLastPage: boolean;\n  nextPageNumber: number | null;\n  currentPage: number;\n  totalPages: number;\n}`,
  ProductDetailResponse: `interface ProductDetailResponse {\n  product: ProductSummary & {\n    variantsDetails?: VariantSetting[];\n    simillerProducts?: ProductSummary[];\n  };\n  simillerProducts?: ProductSummary[];\n}`,
  ProductReviewItem: `interface ProductReviewItem {\n  id: string;\n  rating: number;\n  name: string;\n  email: string;\n  review: string;\n  date?: { _seconds?: number; _nanoseconds?: number } | string;\n  productId?: string;\n}`,
  ProductReviewsResponse: `interface ProductReviewsResponse {\n  items: ProductReviewItem[];\n  isLastPage: boolean;\n  nextPageNumber: number | null;\n  currentPage: number;\n  totalPages: number;\n}`,
  Category: `interface Category {\n  id: string;\n  name: string;\n  description?: string;\n  image?: string;\n  link?: string;\n  subCategories?: CategorySubItem[];\n  productsCount?: number;\n}`,
  LoginRequest: `interface LoginRequest {\n  email: string;\n  password: string;\n}`,
  AuthResponseData: `interface AuthResponseData {\n  user?: CustomerDetails | null;\n  token?: string | null;\n}`,
  CustomerDetails: `interface CustomerDetails {\n  id?: string;\n  name?: string;\n  email?: string;\n  phone?: string;\n  address?: string;\n  gov?: string;\n  storeId?: string;\n  createDate?: { _seconds?: number; _nanoseconds?: number } | string;\n}`,
  StoreData: `interface StoreData {\n  enabled?: boolean;\n  id?: string;\n  name?: string;\n  logo?: string;\n  slogan?: string;\n  country?: string;\n  curreny?: string;\n  domains?: string[];\n  themeing?: StoreThemeing;\n  features?: Record<string, any>;\n  covers?: string[];\n  banners?: string[];\n  depositOptions?: { active?: boolean; type?: string; value?: number };\n  areas?: { govName?: string; price?: number }[];\n  pixels?: Record<string, string>;\n}`,
  // Add more as needed for docs UI
};
